#------------------
# my first action
#------------------

name: My-first-actions-github
on:
 push:
      branches:
        - main

 strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
           
jobs:
  test-one:
    runs-on: ubuntu-latest

    steps:
      - name: git clone project 
        uses: actions/checkout@v2
        
      - name: Project list
        run: ls -la
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with: 
          node-version: ${{ matrix.node-version }}
          
      - name: npm install and start
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
         
      - name: Run a test script
        run: echo Hello, world!


    
