#------------------
# my first action
#------------------

name: My-first-actions-github
on:
 push:
      branches:
        - main

 
           
jobs:
  test-one:
    runs-on: ubuntu-latest
        
    steps:
         - name: git clone project 
           uses: actions/checkout@v2
        
         - name: Project list
           run: ls -la
        
         - name: Install Node.js
           uses: actions/setup-node@v2
           with:
            node-version: 10.x
          
         - name: npm install and start
           run: | 
            npm ci
            npm run build --if-present
            npm test
            npm run build
         


    
