#------------------
# my first action
#------------------

name: My-first-actions-github
on:
 push:
      branches:
        - main

jobs:
  test-one:
    runs-on: ubuntu-latest

    steps:
      - name: git clone project 
        uses: actions/checkout@v2
        
      - name: Project list
        run: ls -la
        
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
         node-version: 10.x
      - name: npm install and start
        run: |
         npm install
         npm start
         
      - name: Run a test script
        run: echo Hello, world!


    
