#------------------
# my first action
#------------------

name: My-first-actions-github
on:
 push:
      branches:
        - main

jobs:
  test-one:
    runs-on: ubuntu-latest

    steps:
      - name: git clone my project
      - uses: actions/checkout@v2
      
      - name: Project list
        run: ls -la
        
      - name: Run a test script
        run: echo Hello, world!
